package com.callistech.analytics.frontend.util;

public enum ActionType {

    CREATE_SUBSCRIBER(0, "Create Subscriber"),
    REMOVE_SUBSCRIBER(1, "Remove Subscriber"),
    EDIT_SUBSCRIBER(2, "Edit Subscriber"),
    USER_LOGIN(3, "User Login"),
    USER_LOGOUT(4, "User Logout"),
    USER_CLEAR_AUDIT(5, "User Clear Audit"),
    USER_IMPORT(6, "User Import"),
    USER_EXPORT(7, "User Export"),
    CREATE_USER(8, "Create user"),
    REMOVE_USER(9, "Remove User"),
    EDIT_USER(10, "Edit User"),
    EDIT_USER_PROFILE(11, "Edit User Profile"),
    CREATE_NEW_USER_PROFILE(12, "Create User Profile"),
    REMOVE_USER_PROFILE(13, "Remove User Profile"),
    CREATE_AD_CAMPAIGN(14, "Create Ad Campaign"),
    DELETE_AD_CAMPAIGN(15, "Delete Ad Campaign"),
    SAVE_AD_CAMPAIGN(16, "Save Ad Campaign"),
    CREATE_ADGROUP(17, "Create Ad Group"),
    SAVE_ADGROUP(18, "Save Ad Group"),
    DELETE_ADGROUP(19, "Delete Ad Group"),
    CREATE_AD(20, "Create Ad"),
    DUPLICATE_AD(21, "Duplicate Ad"),
    DELETE_AD(22, "Delete Ad"),
    SAVE_AD(23, "Save Ad"),
    CREATE_AD_VIEW(24, "Create Ad View"),
    DELETE_AD_VIEW(25, "Delete Ad View"),
    EDIT_AD_VIEW(26, "Edit Ad View"),
    REMOVE_AD_COUNTER(27, "Remove Ad Counter"),
    CREATE_STOP_NOTIFICATION(28, "Create Stop Notification"),
    DELETE_STOP_NOTIFICATION(29, "Delete Stop Notification"),
    UPDATE_STOP_NOTIFICATION(30, "Update Stop Notification"),
    CREATE_CATEGORY(31, "Create Category"),
    EDIT_CATEGORY(32, "Edit Category"),
    REMOVE_CATEGORY(33, "Remove Category"),
    CREATE_CATEGORY_URL(34, "Create Category Url"),
    EDIT_CATEGORY_URL(35, "Edit Category Url"),
    REMOVE_CATEGORY_URL(36, "Remove Category Url"),
    CREATE_SERVICE(37, "Create Service"),
    EDIT_SERVICE(38, "Edit Service"),
    CREATE_POLICY(39, "Create Policy"),
    EDIT_POLICY(40, "Edit Policy"),
    EDIT_RULE(41, "Edit Rule"),
    CREATE_SERVICE_POLICY(42, "Create Service Policy"),
    CREATE_SERVICE_ITEM(43, "Create Service Item"),
    EDIT_CATEGORY_SEP(44, "Edit Category"),
    EDIT_SERVICE_ELEMENT(45, "Edit Service Element"),
    CREATE_FLAVOR_ITEM(46, "Create Flavor Item"),
    EDIT_FLAVOR_ITEM(47, "Edit Flavor Item"),
    CREATE_FLAVOR(48, "Create Flavor"),
    EDIT_FLAVOR(49, "Edit Flavor"),
    CREATE_REDIRECT_PROFILE(50, "Create Redirect Profile"),
    EDIT_REDIRECT_PROFILE(51, "Edit Redirect Profile"),
    CREATE_REDIRECT_PROFILE_ALLOWEDURL(52, "Create Allowed URL"),
    EDIT_REDIRECT_PROFILE_ALLOWEDURL(53, "Edit Allowed URL"),
    REMOVE_SERVICE(54, "Remove Service"),
    REMOVE_POLICY(55, "Remove Policy"),
    REMOVE_SERVICE_POLICY(56, "Remove Service Policy"),
    REMOVE_SERVICE_ELEMENT(57, "Remove Service Element"),
    REMOVE_FLAVOR_ITEM(58, "Remove Flavor Item"),
    REMOVE_FLAVOR(59, "Remove Flavor"),
    REMOVE_REDIRECT_PROFILE(61, "Remove Redirect Profile"),
    REMOVE_REDIRECT_PROFILE_ALLOWEDURL(61, "Remove Allowed URL"),
    CREATE_USER_AGENT(62, "Create User Agent"),
    EDIT_USER_AGENT(63, "Edit User Agent"),
    REMOVE_USER_AGENT(64, "Remove User Agent"),
    CREATE_USER_AGENT_ITEM(65, "Create User Agent Item"),
    EDIT_USER_AGENT_ITEM(66, "Edit User Agent Item"),
    REMOVE_USER_AGENT_ITEM(67, "Remove User Agent Item"),
    CREATE_ZONE(68, "Create Zone"),
    EDIT_ZONE(69, "Edit Zone"),
    REMOVE_ZONE(70, "Remove Zone"),
    CREATE_ZONE_ITEM(71, "Create Zone Item"),
    EDIT_ZONE_ITEM(72, "Edit Zone Item"),
    REMOVE_ZONE_ITEM(73, "Remove Zone Item"),
    CREATE_PROTOCOL(74, "Create Protocol"),
    EDIT_PROTOCOL(75, "Edit Protocol"),
    REMOVE_PROTOCOL(76, "Remove Protocol"),
    CREATE_PROTOCOL_ELEMENT(77, "Create Protocol Element"),
    EDIT_PROTOCOL_ELEMENT(78, "Edit Protocol Element"),
    REMOVE_PROTOCOL_ELEMENT(79, "Remove Protocol Element"),
    CREATE_SUBPORT(80, "Create Subport"),
    DELETE_SUBPORT(81, "Delete Subport"),
    EDIT_SUBPORT(82, "Edit Subport"),
    EDIT_LINKPORT(83, "Edit Linkport"),
    CREATE_RDR_FORMATTER_DESTINATION(84, "Create RDR Formatter Destination"),
    REMOVE_RDR_FORMATTER_DESTINATION(85, "Remove RDR Formatter Destination"),
    EDIT_RDR_FORMATTER_DESTINATION(86, "Edit RDR FOrmatter Destination"),
    CREATE_TAGS(87, "Create Tags"),
    REMOVE_TAGS(88, "Remove Tags"),
    CREATE_ANONYMOUS_GROUP(89, "Create Anonymous Group"),
    CREATE_ANONYMOUS_TEMPLATE(90, "Create Anonymous Template"),
    DELETE_ANONYMOUS_GROUP(91, "Delete Anonymous Group"),
    DELETE_ANONYMOUS_TEMPLATE(92, "Delete Anonymous Template"),
    EDIT_ANONYMOUS_GROUP(93, "Edit Anonymous Group"),
    EDIT_ANONYMOUS_TEMPLATE(94, "Edit Anonymus Template"),
    NAP_CREATE(95, "Create"),
    NAP_DELETE(96, "Delete"),
    NAP_EDIT(97, "Edit"),
    NAP_DUPLICATE(98, "Duplicate"),
    ADD_DND_SUBSCRIBER(99, "Add DND"),
    REMOVE_DND_SUBSCRIBER(100, "Remove DND"),
    EDIT_REDUNDANCY(101, "Redundancy edition."),
    EDIT_VIRTUAL_LINK(102, "Virtual Link edition."),
    ADD_VIRTUAL_LINK(103, "Create Virtual Link."),
    VIRTUAL_LINK_DELETE(104, "Delete Virtual Link."),
    IMPORT_VIRTUAL_LINKS(105, "Import Virtual Links"),
    EXPORT_VIRTUAL_LINKS(106, "Export Virtual Links"),
    SYNCHRONIZATION_VLINK_STANDARD_MODE(107, "Synchronization Virtual Links standard mode"),
    SYNCHRONIZATION_VLINK_FORCE_MODE(108, "Synchronization Virtual Links force mode"),
    REMOVE_VLINK(109, "Remove Virtual Link"),
    ADD_DND_SUBSCRIBER_IMPORT(110, "Add DND on import"),
    REMOVE_DND_SUBSCRIBER_IMPORT(111, "Remove DND on import"),
    USER_IMPORT_DND(112, "User Import DND States"),
    USER_EXPORT_DND(113, "User Export DND States"),
    UNDO_VIRTUAL_LINK(114, "Undo Virtual Link"),
    SYNCHRONIZATION_VLINK(115, "Synchronization Virtual Link"),
    SYNCHRONIZATION_SCE(116, "Synchronization SCE"),
    SET_SETTINGS(1117, "Set Settings "),
    SAVE_RDR_SETTING(1118, "Save RDR Setting"),
    SAVE_IPDR_SETTINGS(1119, "Save IPDR Settings"),
    SAVE_CSV_MANAGER(1120, "Save CSV MAnager"),
    SAVE_DATA_RECORDS_CONFIG(1121, "Save Data Records Config"),
    SAVE_DB_MANAGER(1122, "Save DB Manager"),
    SAVE_OTHERS(1123, "Save Others"),
    NEW_RTA_ADAPTER(1124, "New RTA Adapter"),
    SAVE_RTA_ADAPTER_ALL_CONFIGURATION(125, "Save RTA Adapter all Configuration"),
    DELETE_RTA_ADAPTERS(1126, "Delete RTA Adapters"),
    SAVE_RTA_ADAPTER_GENERAL_CONFIG(1127, "Save RTA Adapter General Config"),
    NEW_PERIODIC(1128, "New Periodic"),
    DELETE_PERIODIC(1129, "Delete Periodic"),
    SAVE_PERIODIC_DATA_RECORD_TASKS(1130, "Save Periodic Data Record Tasks"),
    UPDATEPERIODICQUOTAREFILLTASK(117, "Update Periodic Quota Refill Task"),
    UPDATEPERIODICSUBSCRIBERREMOVALTASK(118, "Update Periodic Subscriber Removal Task"),
    UPDATEPERIODICAUTOLOGINREMOVALTASK(119, "Update Periodic Auto login Removal Task"),
    UPDATEPERIODICAPSESSIONSAGINGTASK(120, "Update Periodic AP Sessions Aging Task"),
    UPDATEPERIODICCAMSESSIONSAGINGTASK(121, "Update Periodic CAM Sessions Aging Task"),
    UPDATEDEFAULTCVPLAN(122, "Update Default CV Plan"),
    UPDATEDEFAULTNONCVPLAN(123, "Update Default NON CV Plan"),
    UPDATEEMAIL(124, "Update Email"),
    UPDATETEMPORARYACCOUNTCV(125, "Update Temporary Account CV"),
    UPDATETEMPORARYACCOUNTNOCV(127, "Update Temporary Account NO CV"),
    EXPORTCAMACCOUNTINGCSV(128, "Export CAM Accounting CSV"),
    EXPORTISGACCOUNTINGCSV(129, "Export Isg Accounting CSV"),
    EXPORTCMACCOUNTINGCSV(130, "Export Cm Accounting CSV"),
    EXPORTEXTERNALACCOUNTINGCSV(131, "Export External Accounting CSV"),
    EXPORTSESSIONSCSV(132, "Export Sessions CSV"),
    REFRESHAPS(133, "Refresh APs"),
    CREATESUBSCRIBERPROFILE(134, "Create Subscriber Profile"),
    EDITSUBSCRIBERPROFILE(135, "Edit Subscriber Profile"),
    REMOVESUBSCRIBERPROFILE(136, "Remove Subscriber Profile"),
    CREATENETWORKOPERATOR(137, "Create Network Operator"),
    EDITNETWORKOPERATOR(138, "Edit Network Operator"),
    REMOVENETWORKOPERATOR(139, "Remove Network Operator"),
    CREATEAAA(140, "Create AAA"),
    EDITAAA(141, "Edit AAA"),
    REMOVEAAA(142, "Remove AAA"),
    CREATEDOMAIN(143, "Create Domain"),
    EDITDOMAIN(144, "Edit Domain"),
    REMOVEDOMAIN(145, "Remove Domain"),
    CREATESUBSCRIBER(146, "Create Subscriber"),
    EDITSUBSCRIBER(147, "Edit Subscriber"),
    REMOVESUBSCRIBER(148, "Remove Subscriber"),
    CREATESUBACCOUNT(149, "Create Subaccount"),
    EDITSUBACCOUNT(150, "Edit Subaccount"),
    REMOVESUBACCOUNT(151, "Remove Subaccount"),
    CREATEPORTAL(152, "Create Portal"),
    EDITPORTAL(153, "Edit Portal"),
    REMOVEPORTAL(154, "Remove Portal"),
    REMOVEPORTALFROMPORTALDESCRIPTION(161, "Remove Portal From Portal Description"),
    DUPLICATEPORTAL(155, "Duplicate Portal"),
    CREATEPORTALURL(156, "CreatePortalURL"),
    EDITPORTALURL(157, "Edit Portal URL"),
    REMOVEPORTALURL(158, "Remove Portal URL"),
    CREATEPORTALLOGINTYPE(159, "Create Portal Login Type"),
    EDITPORTALLOGINTYPE(160, "Edit Portal Login Type"),
    REMOVEPORTALLOGINTYPE(161, "Remove Portal Login Type"),
    CREATEPORTALMAPPING(162, "Create Portal Mapping"),
    EDITPORTALMAPPING(163, "Edit Portal Mapping"),
    REMOVEPORTALMAPPING(164, "Remove Portal Mapping"),
    EDITQUOTAVALUE(165, "Edit Quota Value"),
    CREATEPORTALQUOTAMAPPING(166, "Create Portal Quota Mapping"),
    REMOVEPORTALQUOTAMAPPING(167, "RemovePortalQuotaMapping"),
    CREATEVOUCHERGROUP(168, "Create Voucher Group"),
    EDITVOUCHERGROUP(169, "Edit Voucher Group"),
    REMOVEVOUCHERGROUP(170, "Remove Voucher Group"),
    REMOVEVOUCHERGROUPFROMVOUCHERGROUPNAME(171, "Remove Voucher Group From Voucher Group Name"),
    REMOVEVOUCHER(172, "Remove Voucher"),
    REMOVEPLAN(173, "Remove Plan"),
    REMOVESERVICEFROMPLAN(174, "Remove Service From Plan"),
    REMOVESERVICE(175, "Remove Service"),
    REMOVESERVICEELEMENT(176, "Remove Service Element"),
    REMOVETEMPLATE(177, "Remove Template"),
    REMOVETEMPLATEELEMENT(178, "Remove Template Element"),
    REMOVENETWORKID(179, "Remove Network Id"),
    REMOVEISG(180, "Remove ISG"),
    REMOVEAPGROUP(181, "Remove AP Group"),
    REMOVEAP(182, "Remove AP"),
    REMOVELOCATION(183, "Remove Location"),
    REMOVEWLC(184, "Remove WLC"),
    CREATEVOUCHERS(185, "Create Vouchers"),
    ADDVOUCHERMAPPING(186, "Add Voucher Mapping"),
    REMOVEVOUCHERMAPPING(187, "Remove Voucher Mapping"),
    CREATEPLAN(188, "Create Plan"),
    EDITPLAN(189, "Edit Plan"),
    ADDSERVICETOPLAN(190, "Add Service To Plan"),
    CREATESERVICE(191, "Create Service"),
    EDITSERVICE(192, "Edit Service"),
    ADDSERVICEELEMENT(193, "Add Service Element"),
    EDITSERVICEELEMENT(194, "Edit Service Element"),
    CREATETEMPLATE(195, "Create Template"),
    EDITTEMPLATE(196, "Edit Template"),
    ADDTEMPLATEELEMENT(197, "Add Template Element"),
    EDITTEMPLATEELEMENT(198, "Edit Template Element"),
    CREATENETWORKID(199, "Create Network Id"),
    EDITNETWORKID(200, "Edit Network Id"),
    CREATEISG(201, "Create ISG"),
    EDITISG(202, "Edit ISG"),
    CREATEWLC(203, "Create WLC"),
    EDITWLC(204, "Edit WLC"),
    CREATEAPGROUP(205, "Create AP Group"),
    EDITAPGROUP(206, "Edit AP Group"),
    CREATEAP(207, "Create AP"),
    EDITAP(208, "Edit AP"),
    MOVEALLAPS(209, "Move All APs"),
    TESTMAIL(210, "Test Mail"),
    EXPORTWLCACCOUNTINGCSV(211, "Export WLC Accounting CSV"),
    EXPORTLOCATIONSCSV(212, "Export Locations CSV"),
    SAVESETTINGS(213, "Save Settings"),
    IMPORTZONEITEMS(214, "Import Zone Items"),
    EXPORTZONEITEMS(215, "Export Zone Items"),
    DUPLICATE_POLICY(216,"Duplicate Policy"),
    CREATEOAUTH(217, "Create OAuth"),
    EDITOAUTH(218, "Edit OAuth"),
    REMOVEOAUTH(219, "Remove OAuth");

    private Integer id;

    private String name;

    private ActionType(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}